import type {
  AreaConfig,
  Config,
  Finanzas,
  Historial,
  KaizenState,
  Temporada,
  Usuario,
} from "@/types";
import { hoyISO, sumarDias } from "@/lib/dates";

export const AREAS_DEFAULT: AreaConfig[] = [
  {
    id: "intelecto",
    nombre: "Intelecto",
    dominio: "Academia / Medicina",
    metrica: "Horas de estudio",
    unidad: "h",
    metaDiaria: 4,
    metaSemanalBase: 28,
    topeMetaSemanal: 42,
    peso: 0.35,
    color: "intelecto",
    nivel: 1,
    semanasConsecutivas: 0,
  },
  {
    id: "imperio",
    nombre: "Imperio",
    dominio: "Negocios y finanzas",
    metrica: "Horas de negocio + cumplimiento financiero",
    unidad: "h",
    metaDiaria: 1.5,
    metaSemanalBase: 10,
    topeMetaSemanal: 16,
    peso: 0.15,
    color: "imperio",
    nivel: 1,
    semanasConsecutivas: 0,
  },
  {
    id: "fuerza",
    nombre: "Fuerza",
    dominio: "Gimnasio",
    metrica: "Días entrenados",
    unidad: "días",
    metaDiaria: null,
    metaSemanalBase: 5,
    topeMetaSemanal: 5,
    peso: 0.1,
    color: "fuerza",
    nivel: 1,
    semanasConsecutivas: 0,
  },
  {
    id: "vitalidad",
    nombre: "Vitalidad",
    dominio: "Nutrición",
    metrica: "Comidas correctas",
    unidad: "comidas",
    metaDiaria: 3,
    metaSemanalBase: 21,
    topeMetaSemanal: 21,
    peso: 0.2,
    color: "vitalidad",
    nivel: 1,
    semanasConsecutivas: 0,
  },
  {
    id: "energia",
    nombre: "Energía",
    dominio: "Sueño",
    metrica: "Horas dormidas",
    unidad: "h",
    metaDiaria: 7.5,
    metaSemanalBase: 52.5,
    topeMetaSemanal: 56,
    peso: 0.15,
    color: "energia",
    nivel: 1,
    semanasConsecutivas: 0,
  },
  {
    id: "sabiduria",
    nombre: "Sabiduría",
    dominio: "Aprendizaje",
    metrica: "Páginas leídas",
    unidad: "pág",
    metaDiaria: 15,
    metaSemanalBase: 105,
    topeMetaSemanal: 160,
    peso: 0.05,
    color: "sabiduria",
    nivel: 1,
    semanasConsecutivas: 0,
  },
];

export const USUARIO_DEFAULT: Usuario = {
  nombre: "",
  nivelGlobal: 1,
  ppTotales: 0,
  creditos: 0,
  protecciones: 0,
  tituloActivo: null,
};

export const FINANZAS_DEFAULT: Finanzas = {
  presupuestos: [],
  gastos: [],
  resumenesMensuales: [],
  bancoRecompensas: { saldo: 0, tope: 9000 },
};

export function temporadaDefault(): Temporada {
  const inicio = hoyISO();
  return {
    id: "T1",
    nombre: "Temporada 1",
    narrativa: "El inicio del camino. Cada semana cuenta, ninguna se borra.",
    inicio,
    fin: sumarDias(inicio, 7 * 12 - 1),
    retoFinal: { descripcion: "", completado: false },
    desafios: [],
    eventos: [],
    cerrada: false,
  };
}

export const HISTORIAL_DEFAULT: Historial = {
  temporadas: [],
  records: [],
  reconocimientos: [],
  nivelesMaximos: {
    intelecto: 1,
    imperio: 1,
    fuerza: 1,
    vitalidad: 1,
    energia: 1,
    sabiduria: 1,
  },
};

export const CONFIG_DEFAULT: Config = {
  textos: {
    nombreSistema: "Kaizen",
    atributos: "Áreas de desarrollo",
    xp: "Puntos de Progreso",
    monedas: "Créditos",
    escudos: "Protecciones",
    jefeTemporada: "Reto final de temporada",
    misiones: "Desafíos",
    logros: "Reconocimientos",
    salonFama: "Historial Permanente",
    radar: "Radar de desarrollo",
    tienda: "Catálogo de recompensas",
  },
  economia: {
    ppBase: 1000,
    curvaBase: 800,
    curvaExponente: 1.2,
    creditosPorPP: 20,
    umbralNivelArea: 0.85,
    semanasParaNivelArea: 4,
    incrementoPorEtapa: 0.1,
    nivelesPorEtapa: 5,
    proteccionesMaxAcumulables: 3,
    umbralProteccionMensual: 0.85,
    ventanaProteccionHoras: 48,
    tablaDesbloqueo: [
      { umbral: 0.9, porcentaje: 1.0 },
      { umbral: 0.8, porcentaje: 0.8 },
      { umbral: 0.7, porcentaje: 0.6 },
      { umbral: 0.6, porcentaje: 0.4 },
      { umbral: 0, porcentaje: 0 },
    ],
    bonoRetoFinalPct: 0.1,
    topeBancoRecompensasMeses: 3,
    diasRegistroRetroactivo: 3,
    destinoSobranteDefault: "ahorro",
  },
  imperio: {
    pesoNegocio: 0.5,
    pesoFinanzas: 0.5,
    metaSemanalHorasNegocio: 10,
  },
  bonos: [
    { id: "b_examen", nombre: "Examen aprobado", valorPP: 150 },
    { id: "b_calif", nombre: "Calificación sobre el umbral", valorPP: 100 },
    { id: "b_meta_fin", nombre: "Meta financiera del mes alcanzada", valorPP: 120 },
    { id: "b_record", nombre: "Récord personal en gimnasio", valorPP: 80 },
    { id: "b_proyecto", nombre: "Proyecto entregado", valorPP: 150 },
    { id: "b_desafio", nombre: "Desafío completado", valorPP: 100 },
  ],
  catalogoRecompensas: [
    {
      id: "r_serie",
      nombre: "Noche de serie/película",
      costoCreditos: 20,
      costoMXN: 0,
      categoria: "ocio",
      limitePorMes: 4,
      activa: true,
    },
    {
      id: "r_comida",
      nombre: "Comida fuera",
      costoCreditos: 40,
      costoMXN: 250,
      categoria: "comida",
      limitePorMes: 2,
      activa: true,
    },
    {
      id: "r_compra",
      nombre: "Compra pequeña (ropa, gadget)",
      costoCreditos: 80,
      costoMXN: 600,
      categoria: "compras",
      limitePorMes: 1,
      activa: true,
    },
  ],
  catalogoReconocimientos: [
    {
      id: "ach_racha_4",
      nombre: "Constancia de hierro",
      descripcion: "4 semanas consecutivas sobre el 85% de cumplimiento global.",
      rareza: "Raro",
      categoria: "constancia",
      secreto: false,
    },
    {
      id: "ach_nivel_10",
      nombre: "Doble dígito",
      descripcion: "Alcanza el nivel 10 global.",
      rareza: "Épico",
      categoria: "volumen",
      secreto: false,
    },
    {
      id: "ach_presupuesto_3",
      nombre: "Cuentas claras",
      descripcion: "Cierra 3 meses seguidos dentro de presupuesto.",
      rareza: "Raro",
      categoria: "financiero",
      secreto: false,
    },
    {
      id: "ach_ahorro_total",
      nombre: "Guardián del sobrante",
      descripcion: "Ahorra el 100% del sobrante de una categoría en un mes.",
      rareza: "Común",
      categoria: "financiero",
      secreto: false,
    },
    {
      id: "ach_gastos_90",
      nombre: "Bitácora completa",
      descripcion: "Registra 90 días consecutivos de gastos.",
      rareza: "Épico",
      categoria: "financiero",
      secreto: false,
    },
    {
      id: "ach_temporada_1",
      nombre: "Primera temporada",
      descripcion: "Completa tu primera temporada.",
      rareza: "Legendario",
      categoria: "temporada",
      secreto: false,
    },
    {
      id: "ach_secreto_1",
      nombre: "???",
      descripcion: "Registra tus 6 áreas el mismo día, 7 días seguidos.",
      rareza: "Épico",
      categoria: "constancia",
      secreto: true,
    },
  ],
};

export function estadoInicial(nombreUsuario: string): KaizenState {
  return {
    sistema: { nombre: "Kaizen", version: 2 },
    usuario: { ...USUARIO_DEFAULT, nombre: nombreUsuario },
    areas: AREAS_DEFAULT.map((a) => ({ ...a })),
    registrosDiarios: [],
    finanzas: { ...FINANZAS_DEFAULT, bancoRecompensas: { ...FINANZAS_DEFAULT.bancoRecompensas } },
    cierresSemanales: [],
    canjes: [],
    temporadaActual: temporadaDefault(),
    historial: {
      ...HISTORIAL_DEFAULT,
      nivelesMaximos: { ...HISTORIAL_DEFAULT.nivelesMaximos },
    },
    config: JSON.parse(JSON.stringify(CONFIG_DEFAULT)),
  };
}
